services:
  calcom:
    image: ghcr.io/b2bscaler/cal.com:main
    pull_policy: always

    restart: always

    expose:
      - "3000"

    environment:
      NODE_ENV: "${NODE_ENV}"
      DATABASE_URL: "${DATABASE_URL}"
      DATABASE_DIRECT_URL: "${DATABASE_DIRECT_URL}"
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"
      CALENDSO_ENCRYPTION_KEY: "${CALENDSO_ENCRYPTION_KEY}"
      NEXT_PUBLIC_WEBAPP_URL: "${NEXT_PUBLIC_WEBAPP_URL}"
      NEXT_PUBLIC_WEBSITE_URL: "${NEXT_PUBLIC_WEBSITE_URL}"
      NEXT_PUBLIC_APP_NAME: "B2B Scaler"
      NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS: "info@b2bscaler.com"
      NEXT_PUBLIC_COMPANY_NAME: "B2B Scaler"
      NEXTAUTH_URL: "${NEXTAUTH_URL}"
      WEBAPP_URL: "${WEBAPP_URL}"
      NEXTAUTH_URL_INTERNAL: "${NEXTAUTH_URL_INTERNAL}"
      EMAIL_FROM: "${EMAIL_FROM}"
      EMAIL_FROM_NAME: "${EMAIL_FROM_NAME}"
      RESEND_API_KEY: "${RESEND_API_KEY}"
      DAILY_API_KEY: "${DAILY_API_KEY}"
      DAILY_VIDEO_API_KEY: "${DAILY_VIDEO_API_KEY}"

    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
